name: scan4

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Login to REG
        uses: docker/login-action@v3
        with:
          registry: volcano-ap-southeast-1.cr.bytepluses.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: volcano-ap-southeast-1.cr.bytepluses.com/test/scan4
          file: Dockerfile
      - name: redeploy
        run: curl http://101.47.15.45/6FGS959U9epLIJ6crvu4l2TsdpD4Ozyz2M7JEravear/default/scan4
